require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.6

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Metrics/AbcSize:
  Exclude:
    - 'spec/pages/**/*'
    - 'spec/sections/**/*'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
    - 'lib/solidus_billing_address/factories.rb'

Metrics/LineLength:
  Max: 170

Metrics/MethodLength:
  Exclude:
    - 'spec/pages/**/*'
    - 'spec/sections/**/*'

# Style/ClassAndModuleChildren:
#   Exclude:
#     - 'app/models/spree/payment_method/bank_transfer.rb'

Rails:
  Enabled: true

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
