require: rubocop-rspec

AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.6

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 170

# Style/ClassAndModuleChildren:
#   Exclude:
#     - 'app/models/spree/payment_method/bank_transfer.rb'

Style/Documentation:
  Enabled: false
